### ISSUE TITLE
MidnightMedia issue

### ISSUE THREAD

**Issue by blackhawkworks** [Magisk-Modules-Repo/MidnightCore#4]
Hi,
After installation I tried to run the 'midnight' script from terminal, selected the 'MidnightMedia' option, and got some error messages. Unfortunately I do not have logs nor screenshots of that, I never tought I will need them. Now my phone don't want to boot up anymore, stuck at "Preparing to start... Starting apps...".
Unfortunately I won't be able to debug this issue more, I _have to_ reinstall my phone right now in order to make for example phone calls.

**Environment:**
Blackiew BV6000
LineageOS 13
Latest Magisk

**Steps to reproduce:**
Boot the phone
Install MidnightCore from the Magisk downloads list
Reboot the phone
Open terminal
Run _midnight_
Choose _2 - MidnightMedia_
(fall back to shell with some error, not recorded :( )
Reboot the phone

**Expected result:**
Phone is booting as usual

**Actual result:**
Stuck at
```
Preparing to start...
Starting apps...

```

**Troubleshoot steps I tried:**
Google as obvious
Disable the module with Magisk recovery tool (/data/media/mm)
Uninstall the module
Disable then uninstall all other Magisk modules one by one

**Other info:**
Related piece of logcat:

```
01-01 16:39:13.646   603   928 I ServiceManager: Waiting for service media.audio_policy...
01-01 16:39:14.646   603   928 I ServiceManager: Waiting for service media.audio_policy...
01-01 16:39:15.646   603   928 I ServiceManager: Waiting for service media.audio_policy...
01-01 16:39:15.820  1153  1153 W init    : type=1400 audit(0.0:130): avc: denied { execute_no_trans } for path="/system/bin/memsicd3524x" dev="mmcblk0p26" ino=341 scontext=u:r:init:s0 tcontext=u:object_r:system_file:s0 tclass=file permissive=0
01-01 16:39:15.820  1152  1152 W init    : type=1400 audit(0.0:131): avc: denied { execute_no_trans } for path="/system/xbin/MPED" dev="mmcblk0p26" ino=2625 scontext=u:r:init:s0 tcontext=u:object_r:system_file:s0 tclass=file permissive=0
01-01 16:39:15.839  1154  1154 F libc    : page record for 0x7f82310010 was not found (block_size=16)
01-01 16:39:15.842  1151  1151 F libc    : page record for 0xf728101c was not found (block_size=16)
01-01 16:39:15.881   365   365 I sn      : Retry 18
01-01 16:39:15.881   365   365 I sn      : Fail to access err=2
01-01 16:39:15.881   365   365 I sn      : Fail to access err=2
01-01 16:39:15.881   365   365 I sn      : Fail to access err=2
01-01 16:39:15.881   365   365 I sn      : Check all possible paths
01-01 16:39:16.647   603   928 W AudioSystem: AudioPolicyService not published, waiting...
01-01 16:39:16.840  1159  1159 W init    : type=1400 audit(0.0:132): avc: denied { execute_no_trans } for path="/system/bin/agoldnvram" dev="mmcblk0p26" ino=147 scontext=u:r:init:s0 tcontext=u:object_r:system_file:s0 tclass=file permissive=0
01-01 16:39:16.990   344   344 I thermal_repeater: select timeout
01-01 16:39:17.147   603   928 I ServiceManager: Waiting for service media.audio_policy...
01-01 16:39:18.147   603   928 I ServiceManager: Waiting for service media.audio_policy...

```

**Comment by OldMidnight** [comment]
Ill assume this has been resoled as I've received no other reports of any such errors.
